-- Bon Bon's data model. The same DDL is applied to the linked Supabase project.
-- Product rows are public and read-only. Customer data is private and is only
-- accessed through the authenticated bonbons-data Edge Function.

create schema if not exists private;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  blurb text not null default '',
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  unit text not null default '',
  bundle_eligible boolean not null default false,
  image text not null default '',
  icon text not null default 'i-cakepop',
  color text not null default '#FF2E9A',
  tint text not null default '255,46,154',
  badge text not null default '',
  badge_class text not null default '',
  category text not null default 'everyday',
  lead_time_hours integer not null default 72 check (lead_time_hours >= 0),
  allergens text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_public_catalog_idx
  on public.products (active, sort_order, name);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0),
  subtotal numeric(10, 2) not null default 0 check (subtotal >= 0),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  fulfilment text not null default 'Pickup' check (fulfilment = 'Pickup'),
  wanted_date date not null,
  notes text not null default '',
  admin_notes text not null default '',
  payment_status text not null default 'not_arranged'
    check (payment_status in ('not_arranged', 'instructions_sent', 'paid_cash', 'paid_direct')),
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'confirmed', 'preparing', 'ready', 'collected', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);
create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  event_date date not null,
  occasion text not null default '',
  guests integer check (guests is null or guests > 0),
  fulfilment text not null default 'Pickup' check (fulfilment = 'Pickup'),
  zip text not null default '',
  interests text[] not null default '{}',
  colors text not null default '',
  notes text not null default '',
  admin_notes text not null default '',
  payment_status text not null default 'not_arranged'
    check (payment_status in ('not_arranged', 'instructions_sent', 'paid_cash', 'paid_direct')),
  status text not null default 'new'
    check (status in ('new', 'contacted', 'quoted', 'booked', 'preparing', 'ready', 'closed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quotes_status_created_at_idx
  on public.quotes (status, created_at desc);
create index if not exists quotes_created_at_idx
  on public.quotes (created_at desc);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  source text not null default 'site',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pickup_locations (
  id bigint generated by default as identity primary key,
  label text not null check (length(trim(label)) > 0),
  street_address text not null check (length(trim(street_address)) > 0),
  city text not null check (length(trim(city)) > 0),
  state text not null check (length(trim(state)) > 0),
  postal_code text not null check (length(trim(postal_code)) > 0),
  country text not null check (length(trim(country)) > 0),
  formatted_address text not null check (length(trim(formatted_address)) > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pickup_locations_formatted_address_key
  on public.pickup_locations (lower(formatted_address));
create index if not exists pickup_locations_sort_order_idx
  on public.pickup_locations (sort_order, label);

insert into public.pickup_locations
  (label, street_address, city, state, postal_code, country, formatted_address, sort_order)
values
  ('West Ave', '13435 West Ave', 'San Antonio', 'TX', '78216', 'United States', '13435 West Ave, San Antonio, TX 78216, United States', 10),
  ('Stormy Autumn', '5318 Stormy Autumn', 'San Antonio', 'TX', '78247', 'United States', '5318 Stormy Autumn, San Antonio, TX 78247, United States', 20)
on conflict (lower(formatted_address)) do nothing;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.quotes enable row level security;
alter table public.subscribers enable row level security;
alter table public.pickup_locations enable row level security;

alter table public.products force row level security;
alter table public.orders force row level security;
alter table public.quotes force row level security;
alter table public.subscribers force row level security;
alter table public.pickup_locations force row level security;

revoke all on table public.products from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.quotes from anon, authenticated;
revoke all on table public.subscribers from anon, authenticated;
revoke all on table public.pickup_locations from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on table public.products to anon, authenticated;
grant all on table public.products, public.orders, public.quotes, public.subscribers to service_role;
grant all on table public.pickup_locations to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists products_public_read on public.products;
create policy products_public_read
  on public.products
  for select
  to anon, authenticated
  using (active = true);

-- This project-level event-trigger helper should never be callable through the
-- public API. Not every Supabase project has the helper, so keep this portable.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end
$$;

drop policy if exists orders_deny_public_access on public.orders;
create policy orders_deny_public_access
  on public.orders
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists quotes_deny_public_access on public.quotes;
create policy quotes_deny_public_access
  on public.quotes
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists subscribers_deny_public_access on public.subscribers;
create policy subscribers_deny_public_access
  on public.subscribers
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists pickup_locations_deny_public_access on public.pickup_locations;
create policy pickup_locations_deny_public_access
  on public.pickup_locations
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

-- CRM confirmation details and a shared customer-facing order-number sequence.
create sequence if not exists private.order_number_seq
  as bigint
  start with 1001
  increment by 1
  no cycle;

alter table public.orders
  add column if not exists order_number text,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_total numeric(10, 2)
    check (confirmed_total is null or confirmed_total >= 0),
  add column if not exists pickup_date date,
  add column if not exists pickup_time time,
  add column if not exists pickup_location text not null default '',
  add column if not exists payment_instructions text not null
    default 'Cash at pickup unless the owner provides different instructions.',
  add column if not exists confirmation_sent_at timestamptz,
  add column if not exists last_update_sent_at timestamptz,
  add column if not exists receipt_sent_at timestamptz,
  add column if not exists receipt_email_error text not null default '';

alter table public.quotes
  add column if not exists order_number text,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_total numeric(10, 2)
    check (confirmed_total is null or confirmed_total >= 0),
  add column if not exists pickup_date date,
  add column if not exists pickup_time time,
  add column if not exists pickup_location text not null default '',
  add column if not exists payment_instructions text not null
    default 'Cash at pickup unless the owner provides different instructions.',
  add column if not exists confirmation_sent_at timestamptz,
  add column if not exists last_update_sent_at timestamptz;

create unique index if not exists orders_order_number_key
  on public.orders (order_number)
  where order_number is not null;

create unique index if not exists quotes_order_number_key
  on public.quotes (order_number)
  where order_number is not null;

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  record_kind text not null check (record_kind in ('orders', 'quotes')),
  record_id bigint not null,
  order_number text not null,
  email_type text not null check (email_type in ('request_received', 'confirmation', 'status_update')),
  recipient text not null,
  subject text not null,
  provider_message_id text not null default '',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists email_events_record_idx
  on public.email_events (record_kind, record_id, sent_at desc);

-- Also update databases created before automatic pickup receipts were added.
alter table public.email_events drop constraint if exists email_events_email_type_check;
alter table public.email_events add constraint email_events_email_type_check
  check (email_type in ('request_received', 'confirmation', 'status_update'));

alter table public.email_events enable row level security;
alter table public.email_events force row level security;
revoke all on table public.email_events from anon, authenticated;
grant all on table public.email_events to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists email_events_deny_public_access on public.email_events;
create policy email_events_deny_public_access
  on public.email_events
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function private.assign_order_confirmation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  confirmation_status text;
begin
  confirmation_status := case when tg_table_name = 'orders' then 'confirmed' else 'booked' end;

  if new.status = confirmation_status and new.order_number is null then
    new.order_number :=
      'BB-' || to_char(current_date, 'YY') || '-' ||
      lpad(nextval('private.order_number_seq'::regclass)::text, 4, '0');
    new.confirmed_at := coalesce(new.confirmed_at, now());

    if tg_table_name = 'orders' then
      new.confirmed_total := coalesce(new.confirmed_total, new.subtotal);
      new.pickup_date := coalesce(new.pickup_date, new.wanted_date);
    else
      new.pickup_date := coalesce(new.pickup_date, new.event_date);
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.assign_order_confirmation() from public, anon, authenticated;
grant usage on schema private to service_role;
grant usage, select, update on sequence private.order_number_seq to service_role;
grant execute on function private.assign_order_confirmation() to service_role;

drop trigger if exists assign_order_confirmation_on_orders on public.orders;
create trigger assign_order_confirmation_on_orders
  before insert or update of status, order_number
  on public.orders
  for each row
  execute function private.assign_order_confirmation();

drop trigger if exists assign_order_confirmation_on_quotes on public.quotes;
create trigger assign_order_confirmation_on_quotes
  before insert or update of status, order_number
  on public.quotes
  for each row
  execute function private.assign_order_confirmation();
