-- Bon Bon's data model. The same DDL is applied to the linked Supabase project.
-- Product rows are public and read-only. Customer data is private and is only
-- accessed through the authenticated bonbons-data Edge Function.

create schema if not exists private;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  blurb text not null default '',
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  unit text not null default '',
  bundle_eligible boolean not null default false,
  image text not null default '',
  icon text not null default 'i-cakepop',
  color text not null default '#FF2E9A',
  tint text not null default '255,46,154',
  badge text not null default '',
  badge_class text not null default '',
  category text not null default 'everyday',
  lead_time_hours integer not null default 72 check (lead_time_hours >= 0),
  allergens text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_public_catalog_idx
  on public.products (active, sort_order, name);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0),
  subtotal numeric(10, 2) not null default 0 check (subtotal >= 0),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  fulfilment text not null default 'Pickup' check (fulfilment = 'Pickup'),
  wanted_date date not null,
  notes text not null default '',
  admin_notes text not null default '',
  payment_status text not null default 'not_arranged'
    check (payment_status in ('not_arranged', 'instructions_sent', 'paid_cash', 'paid_direct')),
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'confirmed', 'preparing', 'ready', 'collected', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);
create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  event_date date not null,
  occasion text not null default '',
  guests integer check (guests is null or guests > 0),
  fulfilment text not null default 'Pickup' check (fulfilment = 'Pickup'),
  zip text not null default '',
  interests text[] not null default '{}',
  colors text not null default '',
  notes text not null default '',
  admin_notes text not null default '',
  payment_status text not null default 'not_arranged'
    check (payment_status in ('not_arranged', 'instructions_sent', 'paid_cash', 'paid_direct')),
  status text not null default 'new'
    check (status in ('new', 'contacted', 'quoted', 'booked', 'preparing', 'ready', 'closed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quotes_status_created_at_idx
  on public.quotes (status, created_at desc);
create index if not exists quotes_created_at_idx
  on public.quotes (created_at desc);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  source text not null default 'site',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pickup_locations (
  id bigint generated by default as identity primary key,
  label text not null check (length(trim(label)) > 0),
  street_address text not null check (length(trim(street_address)) > 0),
  city text not null check (length(trim(city)) > 0),
  state text not null check (length(trim(state)) > 0),
  postal_code text not null check (length(trim(postal_code)) > 0),
  country text not null check (length(trim(country)) > 0),
  formatted_address text not null check (length(trim(formatted_address)) > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pickup_locations_formatted_address_key
  on public.pickup_locations (lower(formatted_address));
create index if not exists pickup_locations_sort_order_idx
  on public.pickup_locations (sort_order, label);

insert into public.pickup_locations
  (label, street_address, city, state, postal_code, country, formatted_address, sort_order)
values
  ('West Ave', '13435 West Ave', 'San Antonio', 'TX', '78216', 'United States', '13435 West Ave, San Antonio, TX 78216, United States', 10),
  ('Stormy Autumn', '5318 Stormy Autumn', 'San Antonio', 'TX', '78247', 'United States', '5318 Stormy Autumn, San Antonio, TX 78247, United States', 20)
on conflict (lower(formatted_address)) do nothing;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.quotes enable row level security;
alter table public.subscribers enable row level security;
alter table public.pickup_locations enable row level security;

alter table public.products force row level security;
alter table public.orders force row level security;
alter table public.quotes force row level security;
alter table public.subscribers force row level security;
alter table public.pickup_locations force row level security;

revoke all on table public.products from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.quotes from anon, authenticated;
revoke all on table public.subscribers from anon, authenticated;
revoke all on table public.pickup_locations from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on table public.products to anon, authenticated;
grant all on table public.products, public.orders, public.quotes, public.subscribers to service_role;
grant all on table public.pickup_locations to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists products_public_read on public.products;
create policy products_public_read
  on public.products
  for select
  to anon, authenticated
  using (active = true);

-- This project-level event-trigger helper should never be callable through the
-- public API. Not every Supabase project has the helper, so keep this portable.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end
$$;

drop policy if exists orders_deny_public_access on public.orders;
create policy orders_deny_public_access
  on public.orders
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists quotes_deny_public_access on public.quotes;
create policy quotes_deny_public_access
  on public.quotes
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists subscribers_deny_public_access on public.subscribers;
create policy subscribers_deny_public_access
  on public.subscribers
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists pickup_locations_deny_public_access on public.pickup_locations;
create policy pickup_locations_deny_public_access
  on public.pickup_locations
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

-- CRM confirmation details and a shared customer-facing order-number sequence.
create sequence if not exists private.order_number_seq
  as bigint
  start with 1001
  increment by 1
  no cycle;

alter table public.orders
  add column if not exists order_number text,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_total numeric(10, 2)
    check (confirmed_total is null or confirmed_total >= 0),
  add column if not exists pickup_date date,
  add column if not exists pickup_time time,
  add column if not exists pickup_location text not null default '',
  add column if not exists payment_instructions text not null
    default 'Cash at pickup unless the owner provides different instructions.',
  add column if not exists confirmation_sent_at timestamptz,
  add column if not exists last_update_sent_at timestamptz,
  add column if not exists receipt_sent_at timestamptz,
  add column if not exists receipt_email_error text not null default '';

alter table public.quotes
  add column if not exists order_number text,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_total numeric(10, 2)
    check (confirmed_total is null or confirmed_total >= 0),
  add column if not exists pickup_date date,
  add column if not exists pickup_time time,
  add column if not exists pickup_location text not null default '',
  add column if not exists payment_instructions text not null
    default 'Cash at pickup unless the owner provides different instructions.',
  add column if not exists confirmation_sent_at timestamptz,
  add column if not exists last_update_sent_at timestamptz;

create unique index if not exists orders_order_number_key
  on public.orders (order_number)
  where order_number is not null;

create unique index if not exists quotes_order_number_key
  on public.quotes (order_number)
  where order_number is not null;

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  record_kind text not null check (record_kind in ('orders', 'quotes')),
  record_id bigint not null,
  order_number text not null,
  email_type text not null check (email_type in ('request_received', 'confirmation', 'status_update')),
  recipient text not null,
  subject text not null,
  provider_message_id text not null default '',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists email_events_record_idx
  on public.email_events (record_kind, record_id, sent_at desc);

-- Also update databases created before automatic pickup receipts were added.
alter table public.email_events drop constraint if exists email_events_email_type_check;
alter table public.email_events add constraint email_events_email_type_check
  check (email_type in ('request_received', 'confirmation', 'status_update'));

alter table public.email_events enable row level security;
alter table public.email_events force row level security;
revoke all on table public.email_events from anon, authenticated;
grant all on table public.email_events to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists email_events_deny_public_access on public.email_events;
create policy email_events_deny_public_access
  on public.email_events
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function private.assign_order_confirmation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  confirmation_status text;
begin
  confirmation_status := case when tg_table_name = 'orders' then 'confirmed' else 'booked' end;

  if new.status = confirmation_status and new.order_number is null then
    new.order_number :=
      'BB-' || to_char(current_date, 'YY') || '-' ||
      lpad(nextval('private.order_number_seq'::regclass)::text, 4, '0');
    new.confirmed_at := coalesce(new.confirmed_at, now());

    if tg_table_name = 'orders' then
      new.confirmed_total := coalesce(new.confirmed_total, new.subtotal);
      new.pickup_date := coalesce(new.pickup_date, new.wanted_date);
    else
      new.pickup_date := coalesce(new.pickup_date, new.event_date);
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.assign_order_confirmation() from public, anon, authenticated;
grant usage on schema private to service_role;
grant usage, select, update on sequence private.order_number_seq to service_role;
grant execute on function private.assign_order_confirmation() to service_role;

drop trigger if exists assign_order_confirmation_on_orders on public.orders;
create trigger assign_order_confirmation_on_orders
  before insert or update of status, order_number
  on public.orders
  for each row
  execute function private.assign_order_confirmation();

drop trigger if exists assign_order_confirmation_on_quotes on public.quotes;
create trigger assign_order_confirmation_on_quotes
  before insert or update of status, order_number
  on public.quotes
  for each row
  execute function private.assign_order_confirmation();

-- Box of the Week, owner-controlled pricing, and stock tracking.
-- Mirrors supabase/migrations/20260908010000_weekly_box_and_inventory.sql.
--
-- Everything the feature needs is in this one file, including the privileged
-- write path, so applying it is the only step required. Admin writes go through
-- public.bonbons_admin(), a security-definer function guarded by the same
-- BONBONS_INTERNAL_API_TOKEN the Edge Function already uses. That keeps the
-- trust model identical while removing the need to redeploy the function.

-- stock_quantity is nullable on products on purpose: NULL means "not tracked"
-- (make to order, always available), which is how every existing flavor
-- behaves. 0 means sold out. Existing rows therefore keep working untouched.
alter table public.products
  add column if not exists stock_quantity integer
    check (stock_quantity is null or stock_quantity >= 0),
  add column if not exists low_stock_threshold integer not null default 3
    check (low_stock_threshold >= 0);

-- Shop-wide prices the owner can change without a deploy. Single row, keyed by
-- a constant true so a second row cannot be inserted.
create table if not exists public.shop_settings (
  id boolean primary key default true check (id),
  single_pop_price numeric(10, 2) not null default 4 check (single_pop_price >= 0),
  four_pack_price numeric(10, 2) not null default 10 check (four_pack_price >= 0),
  updated_at timestamptz not null default now()
);

insert into public.shop_settings (id) values (true) on conflict (id) do nothing;

create table if not exists public.weekly_boxes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null check (length(trim(title)) > 0),
  tagline text not null default '',
  description text not null default '',
  price numeric(10, 2) not null default 25 check (price >= 0),
  -- Remaining boxes. Limited runs are the whole point, so this is not nullable.
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  -- The size of the run, so the meter can show "4 of 25 left" rather than a
  -- bar that is always full. Raised automatically whenever stock is restocked.
  initial_stock integer not null default 0 check (initial_stock >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  -- [{ slug, name, qty, note }] — the cake pops inside, with quantities.
  items jsonb not null default '[]'::jsonb
    check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) <= 40),
  image text not null default '',
  -- Exactly one box is the live "this week" box; enforced by a partial index.
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists weekly_boxes_single_featured_idx
  on public.weekly_boxes (featured) where featured;
create index if not exists weekly_boxes_active_idx
  on public.weekly_boxes (active, created_at desc);

alter table public.weekly_boxes enable row level security;
alter table public.shop_settings enable row level security;
alter table public.weekly_boxes force row level security;
alter table public.shop_settings force row level security;

revoke all on table public.weekly_boxes from anon, authenticated;
revoke all on table public.shop_settings from anon, authenticated;

grant select on table public.weekly_boxes to anon, authenticated;
grant select on table public.shop_settings to anon, authenticated;
grant all on table public.weekly_boxes, public.shop_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Shoppers may read the live box and the current prices; nothing else. Writes
-- are impossible through the table itself and must go through bonbons_admin().
drop policy if exists weekly_boxes_public_read on public.weekly_boxes;
create policy weekly_boxes_public_read
  on public.weekly_boxes
  for select
  to anon, authenticated
  using (active = true);

drop policy if exists shop_settings_public_read on public.shop_settings;
create policy shop_settings_public_read
  on public.shop_settings
  for select
  to anon, authenticated
  using (true);

-- Stock is owner-managed rather than decremented at request time. Orders here
-- are requests that staff confirm and are paid offline, so decrementing on
-- submit would let unpaid requests exhaust a limited run. The Shop Desk edits
-- the remaining count as boxes are actually sold.

create extension if not exists pgcrypto with schema extensions;

-- The privileged write path. Callable by anon, but every call must present the
-- server-only internal token; only its SHA-256 is stored here, so reading this
-- definition reveals nothing usable.
create or replace function public.bonbons_admin(
  auth_token text,
  action text,
  payload jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  expected_hash constant text :=
    'ccc8ac8138efd27c19994d11d13b4e41efcc6b1273bfdfb87d39060e35ff0df5';
  target_id bigint;
  wants_featured boolean;
  next_stock integer;
  result jsonb;
begin
  if auth_token is null
     or encode(digest(auth_token, 'sha256'), 'hex') <> expected_hash then
    raise exception 'Unauthorized.' using errcode = '28000';
  end if;

  if action = 'list_weekly_boxes' then
    select coalesce(jsonb_agg(to_jsonb(w) order by w.featured desc, w.created_at desc), '[]'::jsonb)
      into result from public.weekly_boxes w;
    return result;
  end if;

  if action = 'get_shop_settings' then
    select to_jsonb(s) into result from public.shop_settings s limit 1;
    return coalesce(result, 'null'::jsonb);
  end if;

  if action = 'update_shop_settings' then
    insert into public.shop_settings (id, single_pop_price, four_pack_price, updated_at)
    values (true, (payload ->> 'single_pop_price')::numeric,
            (payload ->> 'four_pack_price')::numeric, now())
    on conflict (id) do update
      set single_pop_price = excluded.single_pop_price,
          four_pack_price = excluded.four_pack_price,
          updated_at = now();
    select to_jsonb(s) into result from public.shop_settings s limit 1;
    return result;
  end if;

  if action in ('create_weekly_box', 'update_weekly_box') then
    wants_featured := coalesce((payload ->> 'featured')::boolean, false);
    next_stock := coalesce((payload ->> 'stock_quantity')::integer, 0);

    -- Only one box can be live, so stand the others down before writing.
    if wants_featured then
      update public.weekly_boxes set featured = false, updated_at = now() where featured;
    end if;

    if action = 'create_weekly_box' then
      insert into public.weekly_boxes
        (slug, title, tagline, description, price, stock_quantity, initial_stock,
         low_stock_threshold, items, image, featured, active)
      values (
        payload ->> 'slug',
        payload ->> 'title',
        coalesce(payload ->> 'tagline', ''),
        coalesce(payload ->> 'description', ''),
        (payload ->> 'price')::numeric,
        next_stock,
        next_stock,
        coalesce((payload ->> 'low_stock_threshold')::integer, 5),
        coalesce(payload -> 'items', '[]'::jsonb),
        coalesce(payload ->> 'image', ''),
        wants_featured,
        coalesce((payload ->> 'active')::boolean, true)
      )
      returning to_jsonb(weekly_boxes) into result;
      return result;
    end if;

    target_id := (payload ->> 'id')::bigint;
    update public.weekly_boxes as w set
      slug = payload ->> 'slug',
      title = payload ->> 'title',
      tagline = coalesce(payload ->> 'tagline', ''),
      description = coalesce(payload ->> 'description', ''),
      price = (payload ->> 'price')::numeric,
      stock_quantity = next_stock,
      -- The run size only grows, so selling down keeps the meter honest while
      -- a restock re-baselines it.
      initial_stock = greatest(w.initial_stock, next_stock),
      low_stock_threshold = coalesce((payload ->> 'low_stock_threshold')::integer, 5),
      items = coalesce(payload -> 'items', '[]'::jsonb),
      image = coalesce(payload ->> 'image', ''),
      featured = wants_featured,
      active = coalesce((payload ->> 'active')::boolean, true),
      updated_at = now()
    where w.id = target_id
    returning to_jsonb(w) into result;

    if result is null then
      raise exception 'That box was not found.' using errcode = 'P0002';
    end if;
    return result;
  end if;

  if action = 'delete_weekly_box' then
    delete from public.weekly_boxes where id = (payload ->> 'id')::bigint;
    return jsonb_build_object('ok', true);
  end if;

  -- Price and stock only; the rest of a flavor is still edited through the
  -- existing menu path.
  if action = 'update_product_pricing' then
    update public.products set
      price = (payload ->> 'price')::numeric,
      stock_quantity = case
        when payload ->> 'stock_quantity' is null then null
        else (payload ->> 'stock_quantity')::integer
      end,
      low_stock_threshold = coalesce((payload ->> 'low_stock_threshold')::integer, 3),
      updated_at = now()
    where id = (payload ->> 'id')::bigint
    returning to_jsonb(products) into result;
    if result is null then
      raise exception 'That flavor was not found.' using errcode = 'P0002';
    end if;
    return result;
  end if;

  raise exception 'Unknown admin action: %', action using errcode = '22023';
end;
$fn$;

revoke all on function public.bonbons_admin(text, text, jsonb) from public;
-- Only `anon` and the service role: the Next.js server connects with the
-- publishable key, and signed-in end users never call this. Every call is
-- still gated on the server-only internal token.
grant execute on function public.bonbons_admin(text, text, jsonb) to anon, service_role;

-- Seed a ready-made Celebration Box so the page has something to show the
-- moment this runs: 10 cake pops for $25, built from flavors actually on the
-- menu so every slug points at a real product. Skipped if a box already exists.
with picks as (
  select p.slug, p.name, row_number() over (order by p.sort_order, p.name) as rn
  from public.products p
  where p.active and p.deleted_at is null
  limit 3
)
insert into public.weekly_boxes
  (slug, title, tagline, description, price, stock_quantity, initial_stock,
   low_stock_threshold, items, image, featured, active)
select
  'celebration-box',
  'Celebration Box',
  '10 delicious cake pops. Big variety. Big flavor. Big smiles!',
  'A rotating mix of this week''s flavors, hand-rolled and hand-dipped, then wrapped one at a time. Limited run — once this week''s boxes are claimed, that''s it.',
  25, 20, 20, 5,
  coalesce((
    select jsonb_agg(jsonb_build_object(
      'slug', picks.slug,
      'name', picks.name,
      'qty', case picks.rn when 1 then 4 else 3 end,
      'note', case picks.rn when 1 then 'Top seller' else '' end
    ) order by picks.rn)
    from picks
  ), '[]'::jsonb),
  '/products/bonbons-four-pack-styled.png',
  true, true
where not exists (select 1 from public.weekly_boxes);
