-- Box of the Week, owner-controlled pricing, and stock tracking.
--
-- stock_quantity is nullable on products on purpose: NULL means "not tracked"
-- (make to order, always available), which is how every existing flavor
-- behaves. 0 means sold out. Existing rows therefore keep working untouched.

alter table public.products
  add column if not exists stock_quantity integer
    check (stock_quantity is null or stock_quantity >= 0),
  add column if not exists low_stock_threshold integer not null default 3
    check (low_stock_threshold >= 0);

-- Shop-wide prices the owner can change without a deploy. Single row, keyed by
-- a constant true so a second row cannot be inserted.
create table if not exists public.shop_settings (
  id boolean primary key default true check (id),
  single_pop_price numeric(10, 2) not null default 4 check (single_pop_price >= 0),
  four_pack_price numeric(10, 2) not null default 10 check (four_pack_price >= 0),
  updated_at timestamptz not null default now()
);

insert into public.shop_settings (id) values (true) on conflict (id) do nothing;

create table if not exists public.weekly_boxes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null check (length(trim(title)) > 0),
  tagline text not null default '',
  description text not null default '',
  price numeric(10, 2) not null default 25 check (price >= 0),
  -- Remaining boxes. Limited runs are the whole point, so this is not nullable.
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  -- The size of the run, so the meter can show "4 of 25 left" rather than a
  -- bar that is always full. Raised automatically whenever stock is restocked.
  initial_stock integer not null default 0 check (initial_stock >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  -- [{ name, note }] — what is inside this week's box.
  items jsonb not null default '[]'::jsonb
    check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) <= 40),
  image text not null default '',
  -- Exactly one box is the live "this week" box; enforced by a partial index.
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists weekly_boxes_single_featured_idx
  on public.weekly_boxes (featured) where featured;
create index if not exists weekly_boxes_active_idx
  on public.weekly_boxes (active, created_at desc);

alter table public.weekly_boxes enable row level security;
alter table public.shop_settings enable row level security;
alter table public.weekly_boxes force row level security;
alter table public.shop_settings force row level security;

revoke all on table public.weekly_boxes from anon, authenticated;
revoke all on table public.shop_settings from anon, authenticated;

grant select on table public.weekly_boxes to anon, authenticated;
grant select on table public.shop_settings to anon, authenticated;
grant all on table public.weekly_boxes, public.shop_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Shoppers may read the live box and the current prices; nothing else.
drop policy if exists weekly_boxes_public_read on public.weekly_boxes;
create policy weekly_boxes_public_read
  on public.weekly_boxes
  for select
  to anon, authenticated
  using (active = true);

drop policy if exists shop_settings_public_read on public.shop_settings;
create policy shop_settings_public_read
  on public.shop_settings
  for select
  to anon, authenticated
  using (true);

-- Stock is owner-managed rather than decremented at request time. Orders here
-- are requests that staff confirm and are paid offline, so decrementing on
-- submit would let unpaid requests exhaust a limited run. The Shop Desk edits
-- the remaining count as boxes are actually sold.
